### ISSUE TITLE
Plugin installed but not doing effect

### ISSUE THREAD

**Issue by ivaaane** [bluz71/vim-moonfly-statusline#23]
I installed the status line with `vim-plug` without triggering errors. Vim however only shows the default status line.

This is my `.vimrc`:

```vim
call plug#begin()

Plug 'sheerun/vim-polyglot'
Plug 'jiangmiao/auto-pairs'
Plug 'bluz71/vim-mistfly-statusline'

call plug#end()

set tabstop=8
set shiftwidth=8
set noexpandtab
set number
set numberwidth=1
syntax on

hi LineNr cterm=bold ctermfg=12 guifg=Blue gui=bold
hi CursorLineNr cterm=bold ctermfg=12 guifg=Blue gui=bold

command! Love w | !love .
```

I'm in Vim 9.1 using EndeavourOS and xfce4-terminal. I did `:PlugInstall`, `:PlugUpdate`, `:source .vimrc` and exiting/loading.

**Comment by bluz71** [comment]
You should enable `laststatus` as in:

```vim
set laststatus=2
```

**Comment by ivaaane** [comment]
It's still not working ☹

**Comment by bluz71** [comment]
@ivaaane,

Apologies for the late response, I was very busy yesterday.

I have done quite a bit of experimentation and I am quite sure you have a plugin-manager related issue.

We can confirm that by side-stepping `vim-plug` altogether via this experiment:

```bash
cd ~
mkdir -p .vim/autoload .vim/plugin
git clone https://github.com/bluz71/vim-mistfly-statusline
mv vim-mistfly-statusline/autoload/mistfly.vim .vim/autoload
mv vim-mistfly-statusline/plugin/mistfly-statusline.vim .vim/plugin
vim -c "set laststatus=2"
```

The `mistfly` statusline will now be in effect.

Since you are a `vim-plug` user, in your case, please confirm that `vim-plug` is correctly installed:

```sh
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

Here is a minimal `~/.vimrc` that will work:

```vim
set laststatus=2
set termguicolors
set ttimeoutlen=10

call plug#begin()
Plug 'bluz71/vim-moonfly-colors'
Plug 'bluz71/vim-mistfly-statusline'
call plug#end()

colorscheme moonfly
```

Inside of Vim run `:PlugInstall` to install the plugins, exit Vim and then rerun Vim with plugins in effect.

There is not much else I can do, the `mistfly` statusline does work when the plugin is successfully loaded, that is your debug task.

Best of luck.
