### ISSUE TITLE
Feature Request: Coc.nvim integration

### ISSUE THREAD

**Issue by pinpox** [bluz71/vim-moonfly-statusline#7]
https://github.com/neoclide/coc.nvim/wiki/Statusline-integration

Coc allows for statusline integration. It would be nice to be able to use it inside vim-moonfly-statusline. 
Let me know if you need someone with coc installed to test!

**Comment by bluz71** [comment]
Can you please test the latest update, thanks.

I hope it works, but I don't know until someone actually uses it.

Note, you will also need to enable this new option:

```viml
let g:moonflyWithCocStatus = 1
```

**Comment by pinpox** [comment]
@bluz71 I installed the newest version with vim-plug and set the option you mentioned. 
This is what it looks like without any other configuration:
![image](https://user-images.githubusercontent.com/1719781/91044385-7d5a6800-e615-11ea-9d73-3a213922f830.png)
I'm not sure what is supposed to show, but it looks fine i guess?

**Comment by bluz71** [comment]
To the right of the filename I expect Coc to emit diagnostic errors when auto-linting.

Currently nothing is showing up. Maybe because the current buffer has no errors?

Can you break your code file and see if anything shows up.

**Comment by pinpox** [comment]
It shows `E1`,  `E2`  etc. but not the actual error message:
![image](https://user-images.githubusercontent.com/1719781/91102295-2d0cf580-e669-11ea-9f6f-d37e4ce22c25.png)

**Comment by bluz71** [comment]
I believe this is working.

I would expect the Coc function I am calling to emit very short messages since statuslines often are width constrained. In your case E2, for 2 errors,  seems correct.

The actual error should be displayed via other means, for myself with ALE I use Neovim virtual text feature which displays the error to the right of code when the cursor is stationary on the line with the error.

**Comment by pinpox** [comment]
Okay, then it works! I have virtualtext aswell, like in the image above.

**Comment by bluz71** [comment]
Question, do you prefer E2 or a user definable symbol?

With ALE integration I display just a cross, not count. The cross symbol can be changed by the user.

Should I change the Coc to be similar ALE, for consistency.

**Comment by pinpox** [comment]
I'm okay with both symbols. Having a count could be useful though, so maybe make it configurable?

**Comment by bluz71** [comment]
I will need to stew on this.

I don’t like that ALE and Coc integration into this plugin differ so much.

I may make some changes that may not be compatible. I will be in contact later on once I figure what I want to do.

**Comment by bluz71** [comment]
There are two Coc options available for the moment:

- `g:moonflyWithCocIndicator`, new option similar to existing ALE option, just displays a `✖` if buffer has any diagnostics

- `g:moonflyWithCocStatus`, older option that displays Coc status, for example `E2`

Can you please test the new `let g:moonflyWithCocIndicator = 1` option like you did [here](https://github.com/bluz71/vim-moonfly-statusline/issues/7#issuecomment-679396643).

I am of the belief that `g:moonflyWithCocStatus` should be removed. My thinking is simplicity is preferred since that is the aim of the plugin. Having ALE & Coc both display a simple indicator is the philosophy I am striving for with this plugin.

Thanks.

**Comment by pinpox** [comment]
> let g:moonflyWithCocIndicator = 1

![image](https://user-images.githubusercontent.com/1719781/91129875-01aafa80-e6ab-11ea-9329-8cb3582a3236.png)
![image](https://user-images.githubusercontent.com/1719781/91129958-243d1380-e6ab-11ea-9ec4-66c569eed7a1.png)

Looks good! Im not sure why I seem to have two bars  though if there are some errors. Is it supposed to show like that?

**Comment by bluz71** [comment]
Coc does weird things with statuslines.

I think there are two statuslines because the first one is for the buffer and the second one appears to be for the location list. But it is rendered weirdly.

The blue `normal` indicator should only be displayed for the active window. In ALE the location list displays correctly.

Weird. Does the happen all the time now? Is it new behaviour?

As for the Coc indicator, that does appear to be rendering correctly. I will remove the `g:moonflyWithCocStatus` option. I want to keep this plugin super simple.

**Comment by pinpox** [comment]
Not sure if it's new, but I didn't notice it until now and it's not in the screenshots before. The second bar appears when there is an error. When I start vim with a file with no errors it looks like this:
![image](https://user-images.githubusercontent.com/1719781/91132474-7da64200-e6ad-11ea-8afc-e207bca59731.png)
Then add an error
![image](https://user-images.githubusercontent.com/1719781/91133035-a4fd0f00-e6ad-11ea-8cce-3311a7114572.png)
After it has appeared, the second bar stays, even if the error is removed.
![image](https://user-images.githubusercontent.com/1719781/91133303-b8a87580-e6ad-11ea-8846-248c925747e4.png)
Also notice the `X` error indicator is still there

**Comment by bluz71** [comment]
It looks like the location list does not get removed. Hmmm, something strange is going on, maybe my fault when calling into Coc.

Can you remove `g:moonflyWithCocIndicator` and re-enable `g:moonflyWithCocStatus` like before.

Does the behaviour improve?

**Comment by bluz71** [comment]
Ok,

I installed Coc and there was a bug with `g:moonflyWithCocIndicator`. I believe that should now be resolved. I suspect that will also resolve the double statusline issue.

I have also removed the `g:moonflyWithCocStatus` option. For Coc now you should only set `let g:moonflyWithCocIndicator = 1`.

ALE and Coc are now consistent, just a single indicator, usually `✖`, to indicate any type of diagnostic issue in the current buffer. Super simple. If you don't like the cross indicator then change it via `g:moonflyDiagnosticsIndicator`.

In future I may also add in support for Neovim's inbuilt LSP as well.

I am going to resolve this item since Coc is now supported. If there is still a bug then just open up a new issue. Thanks for testing and providing feedback, it is appreciated.
