### ISSUE TITLE
Feature request:  Tab/buffer line at top

### ISSUE THREAD

**Issue by pinpox** [bluz71/vim-moonfly-statusline#8]
Hey, I thought I'll request another feature, maybe you want to think about it.
In airline I use `let g:airline#extensions#tabline#enabled = 1` to show the buffers and tabs that are open at the top.
Could this be done with vim-moonfly-statusline?

For reference: this is what vim looks with airline's tabline enabled and three buffers open (coc_settings.vim, init.vim, mappings.vim)
![image](https://user-images.githubusercontent.com/1719781/91103940-fdf88300-e66c-11ea-88a4-3f0c7ece1768.png)

**Comment by bluz71** [comment]
Sorry, that is beyond the scope of this plugin.

That airline feature is quite complex since it involves buffer management and taking over the tab line. That’s not really the job of a statusline plugin.

There however should already exist buffer-as-tabs plugins that can do the job.

Maybe this one for example: https://github.com/ap/vim-buftabline

**Comment by pinpox** [comment]
You are right! I was always using the airline integration, but `ap/vim-buftabline` works great for this. Thanks for the recommendation!

**Comment by bluz71** [comment]
Hopefully it works for you.

Seems like you are possibly an airline user looking to transfer away to something lighter?

**Comment by pinpox** [comment]
> Seems like you are possibly an airline user looking to transfer away to something lighter?

That is correct. I have been using airline as it is convenient and easy to setup, but I'd like to replace it with something lighter.
