### ISSUE TITLE
Trim filename in status line

### ISSUE THREAD

**Issue by sleepyArpan** [bluz71/vim-moonfly-statusline#9]
Hey, thanks for this great plugin. I wanted to ask is there a way to trim the filename in the status line to exclude the relative path completely and only display the filename? I have a really nested file and currently the status line looks like `p/w/c/s/A/M/C/C/C/S/filename`

**Comment by bluz71** [comment]
Sorry for the late reply, busy week on my end.

This statusline plugin is designed to display shortened relative paths for nested files and pathless files only for the current directory. So for now your problem has no solution (by design).

My preference is to keep that basic architecture. However, directory path trimming for very long paths does seem reasonable. Maybe something like four path components at most, for example:

- `p/w/c/filename` --> `p/w/c/filename` (no change)
- `p/w/c/s/filename` ---> `.../w/c/s/filename`
- `p/w/c/s/A/M/C/C/C/S/filename` ---> `.../C/C/S/filename`

Ellipses, `...`, like in Bash `PROMPT_DIRTRIM`, can be used to indicate truncation.

Would that suffice? Personally I would probably just implement this and make it the default.

**Comment by bluz71** [comment]
Try the latest update, it now trims paths to a maximum of four components which should largely mitigate your issue whilst also keeping the functionality I like.

Cheers.

**Comment by sleepyArpan** [comment]
Thanks for getting back on this @bluz71 really appreciate it. And yes this will do thank you so much for making this change :D I also wanted to ask is there a way to display the git branch name towards the left of the filename like how airline/lightline do it?

**Comment by bluz71** [comment]
> I also wanted to ask is there a way to display the git branch name towards the left of the filename like how airline/lightline do it?

The positioning of the Git branch is a distinct layout choice which I would like to keep as is (basically because I like it where it is). I also prefer to keep the plugin as simple as possible so I am unlikely to offer an option to change it.

Your best bet would be to fork and move the Git branch to where you like if it is motivating enough.

Cheers.
